

server: 
  port: 8100

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schoolbase?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456 
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis: 
  mapper-locations:
  - classpath*:/mappers/**/*.xml
  type-aliases-package: com.neusoft.managerment.*
                          

logging:
  level:
    com.neusoft.managerment.*: debug
    
neusoftcservice: 
  url: http://localhost:8110/
 